### ISSUE TITLE
Visual Studio crashes

### ISSUE THREAD

**Issue by jtbworld** [Microsoft/dotnet-framework-early-access#51] opened 2018-12-30 04:30 UTC
# Issue Title

Visual Studio 2017 crashes regularly, usually after just a minute or so, while having .NET Framework 4.8 Early Access Build 3707 installed.
After uninstalling 4.8 it worked fine again.

# Version info 

Provide the .NET Framework Early Access build # and your Windows version (output of `winver`).
.NET Framework 4.8 Early Access Build 3707
Windows 10 Version 1809 (OS Build 17763.195)

# General

The following 2 events can be found in the Event Viewer after each crash. 

Log Name:      Application
Source:        .NET Runtime
Date:          2018-12-29 23:29:14
Event ID:      1026
Task Category: None
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      Windows10
Description:
Application: devenv.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException
   at System.Windows.Automation.Peers.ItemAutomationPeer.GetNameCore()
   at System.Windows.Automation.Peers.AutomationPeer.UpdateSubtree()
   at System.Windows.Automation.Peers.AutomationPeer.UpdateSubtree()
   at System.Windows.Automation.Peers.AutomationPeer.UpdateSubtree()
   at System.Windows.Automation.Peers.AutomationPeer.UpdateSubtree()
   at System.Windows.ContextLayoutManager.fireAutomationEvents()
   at System.Windows.ContextLayoutManager.UpdateLayout()
   at System.Windows.UIElement.UpdateLayout()
   at System.Windows.Interop.HwndSource.SetLayoutSize()
   at System.Windows.Interop.HwndSource.set_RootVisualInternal(System.Windows.Media.Visual)
   at System.Windows.Interop.HwndSource.set_RootVisual(System.Windows.Media.Visual)
   at System.Windows.Controls.Primitives.Popup.SetRootVisualToPopupRoot()
   at System.Windows.Controls.Primitives.Popup.CreateWindow(Boolean)
   at System.Windows.Controls.Primitives.Popup.OnIsOpenChanged(System.Windows.DependencyObject, System.Windows.DependencyPropertyChangedEventArgs)
   at System.Windows.DependencyObject.OnPropertyChanged(System.Windows.DependencyPropertyChangedEventArgs)
   at System.Windows.FrameworkElement.OnPropertyChanged(System.Windows.DependencyPropertyChangedEventArgs)
   at System.Windows.DependencyObject.NotifyPropertyChange(System.Windows.DependencyPropertyChangedEventArgs)
   at System.Windows.DependencyObject.UpdateEffectiveValue(System.Windows.EntryIndex, System.Windows.DependencyProperty, System.Windows.PropertyMetadata, System.Windows.EffectiveValueEntry, System.Windows.EffectiveValueEntry ByRef, Boolean, Boolean, System.Windows.OperationType)
   at System.Windows.DependencyObject.SetValueCommon(System.Windows.DependencyProperty, System.Object, System.Windows.PropertyMetadata, Boolean, Boolean, System.Windows.OperationType, Boolean)
   at System.Windows.DependencyObject.SetValue(System.Windows.DependencyProperty, System.Object)
   at Microsoft.VisualStudio.Language.Intellisense.Implementation.LightBulbQuickInfoPlaceHolder.AddLightBulbControlToQuickInfo(Microsoft.VisualStudio.Language.Intellisense.Implementation.LightBulbSession, Microsoft.VisualStudio.Language.Intellisense.Implementation.LightBulbQuickInfoPresenterProvider, Microsoft.VisualStudio.Language.Intellisense.IAsyncQuickInfoSession)
   at Microsoft.VisualStudio.Language.Intellisense.Implementation.LightBulbQuickInfoPresenter.Render()
   at Microsoft.VisualStudio.Language.Intellisense.Implementation.IntellisenseSessionStack.OnSessionPresenterChanged(System.Object, System.EventArgs)
   at Microsoft.VisualStudio.Language.Intellisense.Implementation.BaseIntellisenseSession.RaisePresenterChanged()
   at Microsoft.VisualStudio.Language.Intellisense.Implementation.LightBulbSession.Recalculate()
   at Microsoft.VisualStudio.Language.Intellisense.Implementation.LightBulbSession.Start()
   at Microsoft.VisualStudio.Language.Intellisense.Implementation.LightBulbBroker.CreateSession(Microsoft.VisualStudio.Language.Intellisense.ISuggestedActionCategorySet, Microsoft.VisualStudio.Text.Editor.ITextView, Microsoft.VisualStudio.Text.ITrackingPoint, Microsoft.VisualStudio.Text.ITrackingSpan, System.Collections.Generic.Dictionary`2<Microsoft.VisualStudio.Text.SnapshotSpan,System.Collections.Generic.IEnumerable`1<Microsoft.VisualStudio.Language.Intellisense.ISuggestedActionsSource>>, Microsoft.VisualStudio.Language.Intellisense.ISuggestedActionCategorySet, Boolean, Boolean)
   at Microsoft.VisualStudio.Language.Intellisense.Implementation.LightBulbBroker.CreateSession(Microsoft.VisualStudio.Language.Intellisense.ISuggestedActionCategorySet, Microsoft.VisualStudio.Text.Editor.ITextView, Microsoft.VisualStudio.Text.ITrackingPoint, Microsoft.VisualStudio.Text.ITrackingSpan, Microsoft.VisualStudio.Language.Intellisense.ISuggestedActionCategorySet, Boolean, Boolean)
   at Microsoft.VisualStudio.Language.Intellisense.Implementation.LightBulbBroker.CreateSession(Microsoft.VisualStudio.Language.Intellisense.ISuggestedActionCategorySet, Microsoft.VisualStudio.Text.Editor.ITextView, Microsoft.VisualStudio.Text.ITrackingPoint, Microsoft.VisualStudio.Text.ITrackingSpan, Microsoft.VisualStudio.Language.Intellisense.ISuggestedActionCategorySet, Boolean)
   at Microsoft.VisualStudio.Language.Intellisense.Implementation.LightBulbQuickInfoPlaceHolder+<>c__DisplayClass15_0.<CreateMouseTrackingLightBulbSession>b__0()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(System.Object)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)

Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name=".NET Runtime" />
    <EventID Qualifiers="0">1026</EventID>
    <Level>2</Level>
    <Task>0</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2018-12-30T03:29:14.313321500Z" />
    <EventRecordID>3734</EventRecordID>
    <Channel>Application</Channel>
    <Computer>Windows10</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Application: devenv.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException
   at System.Windows.Automation.Peers.ItemAutomationPeer.GetNameCore()
   at System.Windows.Automation.Peers.AutomationPeer.UpdateSubtree()
   at System.Windows.Automation.Peers.AutomationPeer.UpdateSubtree()
   at System.Windows.Automation.Peers.AutomationPeer.UpdateSubtree()
   at System.Windows.Automation.Peers.AutomationPeer.UpdateSubtree()
   at System.Windows.ContextLayoutManager.fireAutomationEvents()
   at System.Windows.ContextLayoutManager.UpdateLayout()
   at System.Windows.UIElement.UpdateLayout()
   at System.Windows.Interop.HwndSource.SetLayoutSize()
   at System.Windows.Interop.HwndSource.set_RootVisualInternal(System.Windows.Media.Visual)
   at System.Windows.Interop.HwndSource.set_RootVisual(System.Windows.Media.Visual)
   at System.Windows.Controls.Primitives.Popup.SetRootVisualToPopupRoot()
   at System.Windows.Controls.Primitives.Popup.CreateWindow(Boolean)
   at System.Windows.Controls.Primitives.Popup.OnIsOpenChanged(System.Windows.DependencyObject, System.Windows.DependencyPropertyChangedEventArgs)
   at System.Windows.DependencyObject.OnPropertyChanged(System.Windows.DependencyPropertyChangedEventArgs)
   at System.Windows.FrameworkElement.OnPropertyChanged(System.Windows.DependencyPropertyChangedEventArgs)
   at System.Windows.DependencyObject.NotifyPropertyChange(System.Windows.DependencyPropertyChangedEventArgs)
   at System.Windows.DependencyObject.UpdateEffectiveValue(System.Windows.EntryIndex, System.Windows.DependencyProperty, System.Windows.PropertyMetadata, System.Windows.EffectiveValueEntry, System.Windows.EffectiveValueEntry ByRef, Boolean, Boolean, System.Windows.OperationType)
   at System.Windows.DependencyObject.SetValueCommon(System.Windows.DependencyProperty, System.Object, System.Windows.PropertyMetadata, Boolean, Boolean, System.Windows.OperationType, Boolean)
   at System.Windows.DependencyObject.SetValue(System.Windows.DependencyProperty, System.Object)
   at Microsoft.VisualStudio.Language.Intellisense.Implementation.LightBulbQuickInfoPlaceHolder.AddLightBulbControlToQuickInfo(Microsoft.VisualStudio.Language.Intellisense.Implementation.LightBulbSession, Microsoft.VisualStudio.Language.Intellisense.Implementation.LightBulbQuickInfoPresenterProvider, Microsoft.VisualStudio.Language.Intellisense.IAsyncQuickInfoSession)
   at Microsoft.VisualStudio.Language.Intellisense.Implementation.LightBulbQuickInfoPresenter.Render()
   at Microsoft.VisualStudio.Language.Intellisense.Implementation.IntellisenseSessionStack.OnSessionPresenterChanged(System.Object, System.EventArgs)
   at Microsoft.VisualStudio.Language.Intellisense.Implementation.BaseIntellisenseSession.RaisePresenterChanged()
   at Microsoft.VisualStudio.Language.Intellisense.Implementation.LightBulbSession.Recalculate()
   at Microsoft.VisualStudio.Language.Intellisense.Implementation.LightBulbSession.Start()
   at Microsoft.VisualStudio.Language.Intellisense.Implementation.LightBulbBroker.CreateSession(Microsoft.VisualStudio.Language.Intellisense.ISuggestedActionCategorySet, Microsoft.VisualStudio.Text.Editor.ITextView, Microsoft.VisualStudio.Text.ITrackingPoint, Microsoft.VisualStudio.Text.ITrackingSpan, System.Collections.Generic.Dictionary`2&lt;Microsoft.VisualStudio.Text.SnapshotSpan,System.Collections.Generic.IEnumerable`1&lt;Microsoft.VisualStudio.Language.Intellisense.ISuggestedActionsSource&gt;&gt;, Microsoft.VisualStudio.Language.Intellisense.ISuggestedActionCategorySet, Boolean, Boolean)
   at Microsoft.VisualStudio.Language.Intellisense.Implementation.LightBulbBroker.CreateSession(Microsoft.VisualStudio.Language.Intellisense.ISuggestedActionCategorySet, Microsoft.VisualStudio.Text.Editor.ITextView, Microsoft.VisualStudio.Text.ITrackingPoint, Microsoft.VisualStudio.Text.ITrackingSpan, Microsoft.VisualStudio.Language.Intellisense.ISuggestedActionCategorySet, Boolean, Boolean)
   at Microsoft.VisualStudio.Language.Intellisense.Implementation.LightBulbBroker.CreateSession(Microsoft.VisualStudio.Language.Intellisense.ISuggestedActionCategorySet, Microsoft.VisualStudio.Text.Editor.ITextView, Microsoft.VisualStudio.Text.ITrackingPoint, Microsoft.VisualStudio.Text.ITrackingSpan, Microsoft.VisualStudio.Language.Intellisense.ISuggestedActionCategorySet, Boolean)
   at Microsoft.VisualStudio.Language.Intellisense.Implementation.LightBulbQuickInfoPlaceHolder+&lt;&gt;c__DisplayClass15_0.&lt;CreateMouseTrackingLightBulbSession&gt;b__0()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(System.Object)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)

</Data>
  </EventData>
</Event>

Log Name:      Application
Source:        Application Error
Date:          2018-12-29 23:29:15
Event ID:      1000
Task Category: (100)
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      Windows10
Description:
Faulting application name: devenv.exe, version: 15.8.28010.2036, time stamp: 0x5ba2ae3b
Faulting module name: PresentationFramework.ni.dll, version: 4.8.3707.0, time stamp: 0x5c07a66b
Exception code: 0xc0000005
Fault offset: 0x00d360e1
Faulting process id: 0x77c
Faulting application start time: 0x01d49fef5c8742f9
Faulting application path: C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\devenv.exe
Faulting module path: C:\WINDOWS\assembly\NativeImages_v4.0.30319_32\Presentatio5ae0f00f#\b4e6bf52e3735075487c2f59a919f6a9\PresentationFramework.ni.dll
Report Id: eff9785d-3793-4534-9deb-3cf7d80caf73
Faulting package full name: 
Faulting package-relative application ID: 
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Level>2</Level>
    <Task>100</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2018-12-30T03:29:15.141392200Z" />
    <EventRecordID>3735</EventRecordID>
    <Channel>Application</Channel>
    <Computer>Windows10</Computer>
    <Security />
  </System>
  <EventData>
    <Data>devenv.exe</Data>
    <Data>15.8.28010.2036</Data>
    <Data>5ba2ae3b</Data>
    <Data>PresentationFramework.ni.dll</Data>
    <Data>4.8.3707.0</Data>
    <Data>5c07a66b</Data>
    <Data>c0000005</Data>
    <Data>00d360e1</Data>
    <Data>77c</Data>
    <Data>01d49fef5c8742f9</Data>
    <Data>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\devenv.exe</Data>
    <Data>C:\WINDOWS\assembly\NativeImages_v4.0.30319_32\Presentatio5ae0f00f#\b4e6bf52e3735075487c2f59a919f6a9\PresentationFramework.ni.dll</Data>
    <Data>eff9785d-3793-4534-9deb-3cf7d80caf73</Data>
    <Data>
    </Data>
    <Data>
    </Data>
  </EventData>
</Event>

**Comment by vivmishra** [comment] 2019-01-02 19:45
This is a dupe of issue #50 that we plan to fix in next EAP build.

**Closed by vivmishra** 2019-01-02 19:45 UTC

**Comment by ernestogutierrez** [comment] 2019-01-09 21:01
Hi, 

This is happening to me but I haven't found how to uninstall .NET Framework 4.8 Early Access Build.

Thanks,

**Comment by ernestogutierrez** [comment] 2019-01-09 21:37
To uninstall the framework a windows update should be unsintalled:

[How to uninstall .NET Framework 4.8 Early Access Build](https://github.com/Microsoft/dotnet-framework-early-access/blob/master/instructions.md)

**Comment by KiransHub** [comment] 2019-03-18 23:14
I'm getting this with .NET 4.7.2 ?
